using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Anatawa12.AnimatorControllerAsACode.Framework;
using Anatawa12.AnimatorControllerAsACode.VRCAvatars3;
using UnityEditor.Animations;
using UnityEngine;
using Object = UnityEngine.Object;

namespace tokyo.chigiri.worldplace.controllers
{

    public static class AcaacUtilities
    {

        // AccTransition
        public static AccTransitionBase<T> If<T>(this AccTransitionBase<T> transition, params AccParameterCondition[] conditions)
        where T : AnimatorTransitionBase
        {
            foreach (var condition in conditions) transition.When(condition);
            return transition;
        }

        public static AccTransitionBase<T> Raw<T>(this AccTransitionBase<T> transition, Action<AnimatorStateTransition> action)
        where T : AnimatorTransitionBase
        {
            var raw = transition.GetType()
                .GetField("Transition", BindingFlags.Instance | BindingFlags.NonPublic)
                .GetValue(transition) as AnimatorStateTransition;
            action.Invoke(raw);
            return transition;
        }

        // AccState

        public static AccState Sets<T>(this AccState state, AccParameter<T> parameter, T value) where T : unmanaged
        {
            state.SetAvatarParameter(parameter, value);
            return state;
        }

        public static AccState SetsLocal<T>(this AccState state, AccParameter<T> parameter, T value) where T : unmanaged
        {
            state.SetAvatarParameterLocally(parameter, value);
            return state;
        }

        public static AccState Raw(this AccState state, Action<AnimatorState> action)
        {
            var raw = state.GetType()
                .GetField("State", BindingFlags.Instance | BindingFlags.NonPublic)
                .GetValue(state) as AnimatorState;
            action.Invoke(raw);
            return state;
        }

        // AccParameter

        public static AccParameter<T> Raw<T>(this AccParameter<T> parameter, Action<AnimatorControllerParameter> action) where T : unmanaged
        {
            var raw = parameter.GetType()
                .GetField("_parameter", BindingFlags.Instance | BindingFlags.NonPublic)
                .GetValue(parameter) as AnimatorControllerParameter;
            action.Invoke(raw);
            return parameter;
        }

    }

    public class WorldPlace : GeneratorLayerBase
    {

        public Motion localFalseMotion;
        public Motion localTrueMotion;
        public Motion orientationMotion;
        public Motion orientationResetMotion;
        public Motion followingPBMotion;
        public Motion repositionMotion;
        public Motion fixedMotion;
        public Motion[] presetMotions;

        const string WARNING_MESSAGE = "!! DO NOT EDIT (generated by AnimatorControllerAsACode)";

        protected override IEnumerable<Object> WatchingObjects => Array.Empty<Object>();

        protected override void Generate(Acc acc)
        {
            CreateTrigger(acc);
            CreatePresetSelection(acc);
            CreatePosition(acc);
            CreateOrientation(acc);
            CreateLocal(acc);
        }

        private void CreateTrigger(Acc acc)
        {
            var layer = acc.AddLayer("Trigger");
            var triggerParam = layer.BoolParameter("PMC/WorldPlace/API/_Trigger");
            var repositionParam = layer.BoolParameter("PMC/WorldPlace/Reposition");

            var idleState = layer.NewState("Idle");
            var onState = layer.NewState("On").SetsLocal(repositionParam, true);
            var offState = layer.NewState("Off").SetsLocal(repositionParam, false);

            idleState.TransitionsTo(onState).If(triggerParam.IsTrue());
            onState.TransitionsTo(offState).If(triggerParam.IsFalse());
            offState.TransitionsToExit().Raw(t => t.hasExitTime = true);

            layer.NewState(WARNING_MESSAGE).Over(idleState);
        }

        const int PRESET_MAX = 3;

        private static string PresetName(int i) => i==0 ? "Custom" : $"Preset0{i}";

        private static bool Bit(int value, int bit) => (value >> bit & 1) != 0;

        private static AccParameter<bool>[] PresetParams(AccLayer layer) => new []
        {
            layer.BoolParameter("PMC/WorldPlace/Preset/Bit0"),
            layer.BoolParameter("PMC/WorldPlace/Preset/Bit1"),
        };

        private void CreatePresetSelection(Acc acc)
        {
            var layer = acc.AddLayer("PresetSelection");
            var selectParam = layer.IntParameter("PMC/WorldPlace/API/_Preset");
            var presetParams = PresetParams(layer);

            var states = new AccState[PRESET_MAX+1];
            for (var i=0; i<=PRESET_MAX; i++)
            {
                states[i] = layer.NewState(PresetName(i));
                for (var j=0; j<presetParams.Length; j++)
                {
                    states[i].SetsLocal(presetParams[j], Bit(i, j));
                }
                layer.AnyTransitionsTo(states[i]).If(selectParam.IsEqualTo(i));
            }

            layer.NewState(WARNING_MESSAGE).Over(states[0]);
        }

        private void CreatePosition(Acc acc)
        {
            var layer = acc.AddLayer("Position");
            var repositionParam = layer.BoolParameter("PMC/WorldPlace/Reposition");
            var selectParam = layer.IntParameter("PMC/WorldPlace/API/_Preset");
            var presetParams = PresetParams(layer);

            var followingPBState = layer.NewState("FollowingPB").WithAnimation(followingPBMotion);
            var fixedState = layer.NewState("Fixed").WithAnimation(fixedMotion);
            var repositionState = layer.NewState("Reposition").WithAnimation(repositionMotion);
            foreach (var p in presetParams) repositionState.SetsLocal(p, false);

            var presetMachine = layer.NewSubStateMachine("Presets").RightOf(repositionState);
            var presetStates = new AccState[PRESET_MAX];
            for (var i=1; i<=PRESET_MAX; i++)
            {
                presetStates[i-1] = presetMachine.NewState(PresetName(i))
                    .WithAnimation(presetMotions[i-1])
                    .SetsLocal(repositionParam, false);
            }

            followingPBState.TransitionsTo(repositionState).If(repositionParam.IsTrue());
            repositionState.TransitionsTo(fixedState).If(repositionParam.IsFalse());
            fixedState.TransitionsTo(repositionState).If(repositionParam.IsTrue());

            for (var i=1; i<=PRESET_MAX; i++)
            {
                var presetState = presetStates[i-1];
                var presetCond = new AccParameterCondition[presetParams.Length];
                for (var j=0; j<presetParams.Length; j++)
                {
                    var presetParam = presetParams[j];
                    var bit = Bit(i, j);
                    presetCond[j] = bit ? presetParam.IsTrue() : presetParam.IsFalse();
                    presetState.TransitionsTo(repositionState).If(repositionParam.IsTrue(), bit ? presetParam.IsFalse() : presetParam.IsTrue());
                    presetState.TransitionsTo(fixedState).If(repositionParam.IsFalse(), bit ? presetParam.IsFalse() : presetParam.IsTrue());
                }
                followingPBState.TransitionsTo(presetState).If(presetCond);
                repositionState.TransitionsTo(presetState).If(presetCond);
                fixedState.TransitionsTo(presetState).If(presetCond);
            }

            layer.NewState(WARNING_MESSAGE).Over(followingPBState);
        }

        private void CreateOrientation(Acc acc)
        {
            var layer = acc.AddLayer("Orientation");
            var orientationParam = layer.FloatParameter("PMC/WorldPlace/Orientation");
            var presetB1Param = layer.BoolParameter("PMC/WorldPlace/Preset/B1");

            var variableState = layer.NewState("Variable")
                .WithAnimation(orientationMotion)
                .MotionTime(orientationParam);
            var constantState = layer.NewState("Constant")
                .WithAnimation(orientationResetMotion);

            variableState.TransitionsTo(constantState).If(presetB1Param.IsTrue());
            constantState.TransitionsToExit().If(presetB1Param.IsFalse());

            layer.NewState(WARNING_MESSAGE).Over(variableState);
        }

        private void CreateLocal(Acc acc)
        {
            var layer = acc.AddLayer("Local");
            var unlocalParam = layer.BoolParameter("PMC/Common/API/_Unlocal");
            var isLocalParam = layer.BoolParameter("IsLocal");
            var falseState = layer.NewState("False").WithAnimation(localFalseMotion);
            var trueState = layer.NewState("True").WithAnimation(localTrueMotion);

            falseState.TransitionsTo(trueState).If(isLocalParam.IsTrue(), unlocalParam.IsFalse());
            trueState.TransitionsToExit().If(isLocalParam.IsFalse());
            trueState.TransitionsToExit().If(unlocalParam.IsTrue());

            layer.NewState(WARNING_MESSAGE).Over(falseState);
        }

    }

}
